FROM public.ecr.aws/lambda/nodejs:18

# Backend dependencies
WORKDIR /var/task
COPY package*.json ./
RUN npm ci

# Copy backend code
COPY . .

# Frontend dependencies
WORKDIR /var/task/frontend
COPY frontend/package*.json ./
RUN npm ci --omit=dev

# Build frontend
COPY frontend/ ./
RUN npm run build

# Move frontend build to backend build folder
WORKDIR /var/task
RUN mkdir -p build && mv frontend/build/* build/

CMD ["handler.handler"]
