service: jay-user-auth-app
useDotenv: true
provider:
  name: aws
  stage: dev3
  runtime: nodejs18.x
  region: ap-south-1
  deploymentBucket:
    name: ${env:S3_BUCKET}
  tracing:
    lambda: true
    apiGateway: true
  environment:
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:3000
        - https://de0vedacxf.execute-api.ap-south-1.amazonaws.com
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - Authorization
        - X-Amz-Date
        - X-Api-Key
        - X-Amz-Security-Token
      allowCredentials: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: '*'
    - Effect: Allow
      Action:
        - cognito-idp:*
      Resource: '*'
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DescribeTable 
        - dynamodb:Scan
        - dynamodb:Query
      Resource: 
        - arn:aws:dynamodb:ap-south-1:442727737780:table/${env:TableName}
        - arn:aws:dynamodb:ap-south-1:442727737780:table/${env:TableName}/index/*
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:GetObject
        - s3:PutObject
        - s3:HeadObject
      Resource: 
        - arn:aws:s3:::${env:S3_BUCKET}
        - arn:aws:s3:::${env:S3_BUCKET}/*
  ecr:
    images:
      jay-gurnani-user-app:
        path: ./
        file: Dockerfile.lambda
functions:
  api:
    image:
      name: jay-gurnani-user-app
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
    timeout: 10

resources:
  Resources:
    UserProfilesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:TableName}
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST